import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'uz';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Home Page
    'home.badge': 'Gamified Learning Platform',
    'home.hero.title': 'Learn. Grow.',
    'home.hero.titleHighlight': 'Earn Rewards.',
    'home.hero.description': 'IlmCoin is a revolutionary educational platform that combines quality learning with a gamified reward system. Earn coins as you complete lessons, ace quizzes, and achieve your educational goals.',
    'home.hero.getStarted': 'Get Started',
    'home.hero.continueGoogle': 'Continue with Google',
    'home.hero.tryDemo': 'Try Demo Account',
    'home.features.title': 'Why Choose IlmCoin?',
    'home.features.description': 'Experience a new way of learning with features designed to keep you motivated and engaged.',
    'home.features.interactive': 'Interactive Lessons',
    'home.features.interactiveDesc': 'Engage with dynamic courses designed to make learning fun and effective.',
    'home.features.mentor': 'Mentor Support',
    'home.features.mentorDesc': 'Get guidance from experienced mentors who care about your success.',
    'home.features.certificates': 'Certificates & Achievements',
    'home.features.certificatesDesc': 'Earn certificates and badges as you complete courses and reach milestones.',
    'home.features.community': 'Student Community',
    'home.features.communityDesc': 'Connect with peers, share knowledge, and grow together in our vibrant community.',
    'home.features.exploreAll': 'Explore All Features',
    'home.about.title': 'About IlmCoin',
    'home.about.description1': 'IlmCoin was founded with a simple mission: to make learning accessible, enjoyable, and rewarding for everyone. We believe that education should be an exciting journey, not a tedious obligation.',
    'home.about.description2': 'Our platform combines cutting-edge educational content with a unique reward system that motivates students to stay engaged and achieve their goals. Join thousands of learners who are already transforming their educational experience with IlmCoin.',
    'home.about.learnMore': 'Learn More About Us',
    'home.footer.tagline': 'Empowering students through gamified learning and rewards.',
    'home.footer.quickLinks': 'Quick Links',
    'home.footer.resources': 'Resources',
    'home.footer.helpCenter': 'Help Center',
    'home.footer.privacy': 'Privacy Policy',
    'home.footer.terms': 'Terms of Service',
    'home.footer.connect': 'Connect With Us',
    'home.footer.copyright': '© 2025 IlmCoin. All rights reserved.',
    
    // Login Page
    'login.backHome': 'Back to Home',
    'login.title': 'Welcome to IlmCoin',
    'login.subtitle': 'Login to continue your learning journey',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'student@ilmcoin.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.loginButton': 'Login',
    'login.orContinue': 'Or continue with',
    'login.continueGoogle': 'Continue with Google',
    'login.tryDemo': 'Try Demo Account',
    
    // About Page
    'about.title': 'About',
    'about.subtitle': 'Transforming education through innovation, engagement, and rewards.',
    'about.mission.badge': 'Our Mission',
    'about.mission.title': 'Empowering Learners Worldwide',
    'about.mission.desc1': 'At IlmCoin, we believe that education should be accessible, engaging, and rewarding for everyone. Our platform was born from the vision of making learning a joyful experience rather than a burden.',
    'about.mission.desc2': 'We combine cutting-edge technology with proven educational methodologies to create an environment where students are motivated to learn, grow, and achieve their full potential.',
    'about.mission.students': 'Active Students',
    'about.mission.courses': 'Courses',
    'about.why.title': 'Why Choose IlmCoin?',
    'about.why.description': 'Discover what makes our platform the perfect choice for your learning journey.',
    'about.why.goals': 'Clear Learning Goals',
    'about.why.goalsDesc': 'Set and track your educational objectives with our structured curriculum and personalized learning paths.',
    'about.why.progress': 'Track Your Progress',
    'about.why.progressDesc': 'Monitor your improvement with detailed analytics and insights into your learning journey.',
    'about.why.secure': 'Safe & Secure',
    'about.why.secureDesc': 'Your data is protected with industry-standard security measures and privacy protocols.',
    'about.why.centered': 'Student-Centered',
    'about.why.centeredDesc': 'Every feature is designed with students in mind, ensuring an engaging and supportive experience.',
    'about.team.title': 'Meet Our Team',
    'about.team.description': 'Passionate educators and technologists working together to revolutionize learning.',
    'about.cta.title': 'Ready to Start Your Journey?',
    'about.cta.description': 'Join thousands of students who are already learning, growing, and earning rewards with IlmCoin.',
    'about.cta.getStarted': 'Get Started Now',
    'about.cta.exploreFeatures': 'Explore Features',
    
    // Features Page
    'features.title': 'Platform',
    'features.titleHighlight': 'Features',
    'features.subtitle': 'Discover all the powerful tools and features designed to make your learning experience exceptional.',
    'features.reward.title': 'Reward Coins System',
    'features.reward.description': 'Earn IlmCoins for every lesson completed, quiz passed, and milestone achieved. Redeem your coins for certificates, premium courses, and exclusive content.',
    'features.reward.feature1': 'Earn coins for completing lessons',
    'features.reward.feature2': 'Bonus rewards for streaks',
    'features.reward.feature3': 'Redeem for premium content',
    'features.reward.feature4': 'Track your earning history',
    'features.interactive.title': 'Interactive Courses',
    'features.interactive.description': 'Access a vast library of courses across multiple subjects, all designed with interactive elements to keep you engaged and motivated throughout your learning journey.',
    'features.interactive.feature1': 'Video lessons with quizzes',
    'features.interactive.feature2': 'Hands-on projects',
    'features.interactive.feature3': 'Downloadable resources',
    'features.interactive.feature4': 'Self-paced learning',
    'features.achievements.title': 'Achievements & Certificates',
    'features.achievements.description': 'Showcase your accomplishments with digital badges and certificates. Build your portfolio and demonstrate your skills to potential employers or educational institutions.',
    'features.achievements.feature1': 'Digital certificates',
    'features.achievements.feature2': 'Skill badges',
    'features.achievements.feature3': 'Shareable achievements',
    'features.achievements.feature4': 'Portfolio building',
    'features.dashboard.title': 'Student Dashboard',
    'features.dashboard.description': 'Monitor your progress with comprehensive analytics. Track your learning patterns, identify strengths, and discover areas for improvement with detailed insights.',
    'features.dashboard.feature1': 'Progress tracking',
    'features.dashboard.feature2': 'Performance analytics',
    'features.dashboard.feature3': 'Learning insights',
    'features.dashboard.feature4': 'Goal setting tools',
    'features.mentorship.title': 'Mentorship & Support',
    'features.mentorship.description': 'Connect with experienced mentors who provide personalized guidance, answer questions, and help you navigate your educational journey with expert advice.',
    'features.mentorship.feature1': 'One-on-one mentoring',
    'features.mentorship.feature2': '24/7 support chat',
    'features.mentorship.feature3': 'Community forums',
    'features.mentorship.feature4': 'Expert guidance',
    'features.live.title': 'Live Sessions',
    'features.live.description': 'Participate in live interactive sessions with instructors and fellow students. Engage in real-time discussions and get immediate answers to your questions.',
    'features.live.feature1': 'Live webinars',
    'features.live.feature2': 'Q&A sessions',
    'features.live.feature3': 'Interactive workshops',
    'features.live.feature4': 'Recording access',
    'features.additional.title': 'And Much More...',
    'features.additional.forums': 'Discussion Forums',
    'features.additional.forumsDesc': 'Engage with community',
    'features.additional.secure': 'Secure Platform',
    'features.additional.secureDesc': 'Your data is protected',
    'features.additional.quick': 'Quick Learning',
    'features.additional.quickDesc': 'Learn at your pace',
    'features.additional.goals': 'Goal Tracking',
    'features.additional.goalsDesc': 'Set and achieve goals',
    'features.additional.reminders': 'Smart Reminders',
    'features.additional.remindersDesc': 'Stay on track',
    'features.additional.reports': 'Progress Reports',
    'features.additional.reportsDesc': 'Detailed insights',
    'features.keyFeatures': 'Key Features:',
    'features.cta.title': 'Ready to Experience All These Features?',
    'features.cta.description': 'Join IlmCoin today and unlock a world of interactive learning, rewards, and achievements.',
    'features.cta.start': 'Start Learning Now',
    'features.cta.contact': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Get in',
    'contact.titleHighlight': 'Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.namePlaceholder': 'John Doe',
    'contact.form.email': 'Email Address',
    'contact.form.emailPlaceholder': 'john@example.com',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us how we can help you...',
    'contact.form.send': 'Send Message',
    'contact.form.sent': 'Message Sent!',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'contact.hours.title': 'Office Hours',
    'contact.hours.weekday': 'Monday - Friday',
    'contact.hours.weekdayTime': '9:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturdayTime': '10:00 AM - 4:00 PM',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sundayTime': 'Closed',
    'contact.social.title': 'Follow Us',
    'contact.map.title': 'Interactive Map',
    'contact.map.description': 'Find us at 123 Education Street',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back,',
    'dashboard.subtitle': 'Track your learning progress and rewards',
    'dashboard.totalCoins': 'Total Coins',
    'dashboard.thisWeek': 'this week',
    'dashboard.achievements': 'Achievements',
    'dashboard.newMonth': 'new this month',
    'dashboard.streak': 'Current Streak',
    'dashboard.days': 'Days',
    'dashboard.keepUp': 'Keep it up!',
    'dashboard.rewardHistory': 'Reward History',
    'dashboard.trackAll': 'Track all your earned coins and achievements',
    'dashboard.filterType': 'Filter by type',
    'dashboard.allActivities': 'All Activities',
    'dashboard.homework': 'Homework',
    'dashboard.quizzes': 'Quizzes',
    'dashboard.achievements': 'Achievements',
    'dashboard.participation': 'Participation',
    'dashboard.bonus': 'Bonus',
    'dashboard.referrals': 'Referrals',
    'dashboard.noActivities': 'No activities found for this filter',
    'dashboard.home': 'Home',
    'dashboard.dashboard': 'Dashboard',
    'dashboard.courses': 'My Courses',
    'dashboard.profile': 'Profile',
    
    // Activities
    'activity.completedMathQuiz': 'Completed Advanced Mathematics Quiz',
    'activity.submittedPhysics': 'Submitted Physics Assignment',
    'activity.learningStreak': '7-Day Learning Streak',
    'activity.activeDiscussion': 'Active Discussion Participation',
    'activity.acedEnglish': 'Aced English Literature Test',
    'activity.earlySubmission': 'Early Submission Bonus',
    'activity.chemistryLab': 'Chemistry Lab Report',
    'activity.referredFriend': 'Referred a Friend',
    'activity.completedCourse': 'Completed Course: Web Development',
    'activity.historyQuiz': 'History Quiz Perfect Score',
    
    // Categories
    'category.math': 'Math',
    'category.science': 'Science',
    'category.milestone': 'Milestone',
    'category.community': 'Community',
    'category.english': 'English',
    'category.bonus': 'Bonus',
    'category.referral': 'Referral',
    'category.achievement': 'Achievement',
    'category.history': 'History',
    
    // Team Members
    'team.ceo': 'CEO & Founder',
    'team.cto': 'Chief Technology Officer',
    'team.education': 'Head of Education',
    'team.product': 'Product Manager',
    
    // Leaderboard
    'leaderboard.title': 'Leaderboard',
    'leaderboard.subtitle': 'Top performers and their achievements',
    'leaderboard.students': 'Students',
    'leaderboard.teachers': 'Teachers',
    'leaderboard.admins': 'Admins',
    'leaderboard.rank': 'Rank',
    'leaderboard.name': 'Name',
    'leaderboard.currentBalance': 'Current Balance',
    'leaderboard.allTimeBalance': 'All-Time Balance',
    'leaderboard.actions': 'Actions',
    'leaderboard.current': 'Current',
    'leaderboard.allTime': 'All-Time',
    'leaderboard.view': 'View',
    'leaderboard.hide': 'Hide',
    'leaderboard.transactionHistory': 'Transaction History',
    'leaderboard.type': 'Type',
    'leaderboard.description': 'Description',
    'leaderboard.amount': 'Amount',
    'leaderboard.date': 'Date',
    'leaderboard.page': 'Page',
    'leaderboard.of': 'of',
    'leaderboard.previous': 'Previous',
    'leaderboard.next': 'Next',
    'leaderboard.topPerformer': 'Top Performer',
    'leaderboard.excellent': 'Excellent',
    'leaderboard.great': 'Great',
  },
  uz: {
    // Navigation
    'nav.home': 'Bosh sahifa',
    'nav.about': 'Biz haqimizda',
    'nav.features': 'Imkoniyatlar',
    'nav.contact': 'Aloqa',
    'nav.login': 'Kirish',
    'nav.logout': 'Chiqish',
    
    // Home Page
    'home.badge': 'Oʻyinlashtirish bilan oʻqitish platformasi',
    'home.hero.title': 'Oʻrgan. Oʻs.',
    'home.hero.titleHighlight': 'Mukofot qozon.',
    'home.hero.description': 'IlmCoin - bu sifatli ta\'limni oʻyinlashtirish mukofotlar tizimi bilan birlashtiradigan inqilobiy ta\'lim platformasi. Darslarni tugatib, testlardan oʻtib, ta\'lim maqsadlaringizga erishib tangalar qazoning.',
    'home.hero.getStarted': 'Boshlash',
    'home.hero.continueGoogle': 'Google orqali davom etish',
    'home.hero.tryDemo': 'Demo hisobni sinab koʻring',
    'home.features.title': 'Nima uchun IlmCoin?',
    'home.features.description': 'Sizni motivatsiyalangan va jalb qilishga moʻljallangan xususiyatlar bilan yangicha oʻqitishni boshdan kechiring.',
    'home.features.interactive': 'Interaktiv darslar',
    'home.features.interactiveDesc': 'Oʻqishni qiziqarli va samarali qilish uchun moʻljallangan dinamik kurslar bilan mashgʻul boʻling.',
    'home.features.mentor': 'Murabbiy yordami',
    'home.features.mentorDesc': 'Muvaffaqiyatingiz haqida qayğʻuradigan tajribali murabbiylardan yoʻl-yoʻriq oling.',
    'home.features.certificates': 'Sertifikatlar va yutuqlar',
    'home.features.certificatesDesc': 'Kurslarni tugatib, muhim bosqichlarga erishganingizda sertifikatlar va nishonlar qazoning.',
    'home.features.community': 'Talabalar jamiyati',
    'home.features.communityDesc': 'Tengdoshlaringiz bilan bogʻlaning, bilim almashing va jonli jamiyatimizda birgalikda oʻsing.',
    'home.features.exploreAll': 'Barcha imkoniyatlarni koʻring',
    'home.about.title': 'IlmCoin haqida',
    'home.about.description1': 'IlmCoin oddiy missiya bilan tashkil etilgan: ta\'limni hamma uchun qulay, yoqimli va mukofotlovchi qilish. Biz ta\'lim zerikarli majburiyat emas, balki qiziqarli sayohat boʻlishi kerakligiga ishonamiz.',
    'home.about.description2': 'Bizning platformamiz zamonaviy ta\'lim mazmunini talabalarni jalb qilish va maqsadlariga erishishga undaydigan noyob mukofotlar tizimi bilan birlashtiradi. IlmCoin bilan ta\'lim tajribasini allaqachon oʻzgartirayotgan minglab oʻquvchilarga qoʻshiling.',
    'home.about.learnMore': 'Biz haqimizda koʻproq',
    'home.footer.tagline': 'Talabalarni oʻyinlashtirish va mukofotlar orqali rivojlantirish.',
    'home.footer.quickLinks': 'Tezkor havolalar',
    'home.footer.resources': 'Resurslar',
    'home.footer.helpCenter': 'Yordam markazi',
    'home.footer.privacy': 'Maxfiylik siyosati',
    'home.footer.terms': 'Foydalanish shartlari',
    'home.footer.connect': 'Biz bilan bogʻlaning',
    'home.footer.copyright': '© 2025 IlmCoin. Barcha huquqlar himoyalangan.',
    
    // Login Page
    'login.backHome': 'Bosh sahifaga',
    'login.title': 'IlmCoin ga xush kelibsiz',
    'login.subtitle': 'Oʻquv sayohatingizni davom ettirish uchun kiring',
    'login.email': 'Elektron pochta',
    'login.emailPlaceholder': 'talaba@ilmcoin.com',
    'login.password': 'Parol',
    'login.passwordPlaceholder': '••••••••',
    'login.loginButton': 'Kirish',
    'login.orContinue': 'Yoki davom eting',
    'login.continueGoogle': 'Google orqali davom etish',
    'login.tryDemo': 'Demo hisobni sinab koʻring',
    
    // About Page
    'about.title': 'Biz haqimizda',
    'about.subtitle': 'Innovatsiya, jalb qilish va mukofotlar orqali ta\'limni oʻzgartirish.',
    'about.mission.badge': 'Bizning missiyamiz',
    'about.mission.title': 'Butun dunyo boʻylab oʻquvchilarni rivojlantirish',
    'about.mission.desc1': 'IlmCoin da biz ta\'lim hamma uchun qulay, qiziqarli va mukofotlovchi boʻlishi kerakligiga ishonamiz. Bizning platformamiz ta\'limni yuk emas, balki quvonchli tajribaga aylantirish g\'oyasidan tugʻilgan.',
    'about.mission.desc2': 'Biz zamonaviy texnologiyani isbotlangan ta\'lim metodologiyalari bilan birlashtiramiz, shunda talabalar oʻrganish, oʻsish va oʻzlarining toʻliq salohiyatiga erishishga undaydilar.',
    'about.mission.students': 'Faol talabalar',
    'about.mission.courses': 'Kurslar',
    'about.why.title': 'Nima uchun IlmCoin?',
    'about.why.description': 'Platformamizni oʻquv sayohatingiz uchun ajoyib tanlov qiluvchi narsalarni kashf eting.',
    'about.why.goals': 'Aniq oʻrganish maqsadlari',
    'about.why.goalsDesc': 'Tuzilgan oʻquv dasturimiz va shaxsiy oʻquv yoʻllaringiz bilan ta\'lim maqsadlaringizni belgilang va kuzatib boring.',
    'about.why.progress': 'Rivojlanishingizni kuzating',
    'about.why.progressDesc': 'Oʻquv sayohatingizga batafsil tahlil va tushunchalar bilan yaxshilanishingizni kuzatib boring.',
    'about.why.secure': 'Xavfsiz va ishonchli',
    'about.why.secureDesc': 'Maʼlumotlaringiz sanoat standartidagi xavfsizlik choralari va maxfiylik protokollari bilan himoyalangan.',
    'about.why.centered': 'Talabaga yoʻnaltirilgan',
    'about.why.centeredDesc': 'Har bir xususiyat talabalar uchun moʻljallangan, qiziqarli va qoʻllab-quvvatlovchi tajribani taʼminlaydi.',
    'about.team.title': 'Bizning jamoamiz',
    'about.team.description': 'Ta\'limni inqilob qilish uchun birgalikda ishlaydigan ishtiyoqli pedagog va texnologlar.',
    'about.cta.title': 'Sayohatingizni boshlashga tayyormisiz?',
    'about.cta.description': 'IlmCoin bilan allaqachon oʻrganayotgan, oʻsayotgan va mukofot qozonayotgan minglab talabalarga qoʻshiling.',
    'about.cta.getStarted': 'Hoziroq boshlang',
    'about.cta.exploreFeatures': 'Imkoniyatlarni koʻrish',
    
    // Features Page
    'features.title': 'Platforma',
    'features.titleHighlight': 'imkoniyatlari',
    'features.subtitle': 'Oʻquv tajribangizni ajoyib qilish uchun moʻljallangan barcha kuchli vositalar va xususiyatlarni kashf eting.',
    'features.reward.title': 'Mukofot tangalari tizimi',
    'features.reward.description': 'Har bir tugatilgan dars, oʻtilgan test va erishilgan muhim bosqich uchun IlmCoin qazoning. Tangalaringizni sertifikatlar, premium kurslar va maxsus kontent uchun almashiring.',
    'features.reward.feature1': 'Darslarni tugatib tangalar qazoning',
    'features.reward.feature2': 'Ketma-ketlik uchun bonus mukofotlar',
    'features.reward.feature3': 'Premium kontent uchun almashing',
    'features.reward.feature4': 'Daromadlar tarixini kuzatib boring',
    'features.interactive.title': 'Interaktiv kurslar',
    'features.interactive.description': 'Koʻp fanlar boʻyicha keng kutubxonaga kiring, barchasi sizni butun oʻquv sayohatingiz davomida jalb qilish va motivatsiyalash uchun interaktiv elementlar bilan moʻljallangan.',
    'features.interactive.feature1': 'Testlar bilan video darslar',
    'features.interactive.feature2': 'Amaliy loyihalar',
    'features.interactive.feature3': 'Yuklab olinadigan resurslar',
    'features.interactive.feature4': 'Oʻz sur\'atingizda oʻrganish',
    'features.achievements.title': 'Yutuqlar va sertifikatlar',
    'features.achievements.description': 'Raqamli nishonlar va sertifikatlar bilan yutuqlaringizni koʻrsating. Portfolio yaratib, koʻnikmalaringizni potentsial ish beruvchilarga yoki ta\'lim muassasalariga namoyish eting.',
    'features.achievements.feature1': 'Raqamli sertifikatlar',
    'features.achievements.feature2': 'Koʻnikma nishonlari',
    'features.achievements.feature3': 'Ulashish mumkin boʻlgan yutuqlar',
    'features.achievements.feature4': 'Portfolio yaratish',
    'features.dashboard.title': 'Talaba paneli',
    'features.dashboard.description': 'Keng qamrovli tahlil bilan rivojlanishingizni kuzatib boring. Oʻquv naqshlaringizni kuzating, kuchli tomonlarni aniqlang va batafsil tushunchalar bilan yaxshilash sohalarini kashf eting.',
    'features.dashboard.feature1': 'Rivojlanishni kuzatish',
    'features.dashboard.feature2': 'Faoliyat tahlili',
    'features.dashboard.feature3': 'Oʻrganish tushunchalari',
    'features.dashboard.feature4': 'Maqsad belgilash vositalari',
    'features.mentorship.title': 'Murabbiylik va qoʻllab-quvvatlash',
    'features.mentorship.description': 'Shaxsiy yoʻl-yoʻriq beruvchi, savollarga javob beruvchi va ta\'lim sayohatingizda mutaxassis maslahatlari bilan yordam beruvchi tajribali murabbiylar bilan bogʻlaning.',
    'features.mentorship.feature1': 'Yakkama-yakka murabbiylik',
    'features.mentorship.feature2': '24/7 qoʻllab-quvvatlash chat',
    'features.mentorship.feature3': 'Jamiyat forumlari',
    'features.mentorship.feature4': 'Mutaxassis yoʻl-yoʻriqi',
    'features.live.title': 'Jonli seanslar',
    'features.live.description': 'Oʻqituvchilar va boshqa talabalar bilan jonli interaktiv seanslarda qatnashing. Real vaqtdagi muhokamalar va savollaringizga zudlik bilan javoblar oling.',
    'features.live.feature1': 'Jonli vebinarlar',
    'features.live.feature2': 'Savol-javob seanslari',
    'features.live.feature3': 'Interaktiv ustaxonalar',
    'features.live.feature4': 'Yozuvlarga kirish',
    'features.additional.title': 'Va yana koʻp narsalar...',
    'features.additional.forums': 'Muhokama forumlari',
    'features.additional.forumsDesc': 'Jamiyat bilan muloqot qiling',
    'features.additional.secure': 'Xavfsiz platforma',
    'features.additional.secureDesc': 'Maʼlumotlaringiz himoyalangan',
    'features.additional.quick': 'Tez oʻrganish',
    'features.additional.quickDesc': 'Oʻz sur\'atingizda oʻrganing',
    'features.additional.goals': 'Maqsadlarni kuzatish',
    'features.additional.goalsDesc': 'Maqsadlarni belgilang va erishing',
    'features.additional.reminders': 'Aqlli eslatmalar',
    'features.additional.remindersDesc': 'Yoʻlda qoling',
    'features.additional.reports': 'Rivojlanish hisobotlari',
    'features.additional.reportsDesc': 'Batafsil tushunchalar',
    'features.keyFeatures': 'Asosiy xususiyatlar:',
    'features.cta.title': 'Barcha xususiyatlarni sinab koʻrishga tayyormisiz?',
    'features.cta.description': 'Bugun IlmCoin ga qoʻshiling va interaktiv oʻrganish, mukofotlar va yutuqlar dunyosini oching.',
    'features.cta.start': 'Hoziroq oʻrganishni boshlang',
    'features.cta.contact': 'Biz bilan bogʻlaning',
    
    // Contact Page
    'contact.title': 'Biz bilan',
    'contact.titleHighlight': 'bogʻlaning',
    'contact.subtitle': 'Savollaringiz bormi? Sizdan eshitishni xohlaymiz. Xabar yuboring va imkon qadar tezroq javob beramiz.',
    'contact.form.title': 'Xabar yuboring',
    'contact.form.name': 'Ismingiz',
    'contact.form.namePlaceholder': 'Anvar Aliyev',
    'contact.form.email': 'Elektron pochta',
    'contact.form.emailPlaceholder': 'anvar@example.com',
    'contact.form.message': 'Xabar',
    'contact.form.messagePlaceholder': 'Sizga qanday yordam bera olishimizni ayting...',
    'contact.form.send': 'Xabar yuborish',
    'contact.form.sent': 'Xabar yuborildi!',
    'contact.form.success': 'Xabar muvaffaqiyatli yuborildi! Tez orada sizga javob beramiz.',
    'contact.info.title': 'Aloqa maʼlumotlari',
    'contact.info.email': 'Elektron pochta',
    'contact.info.phone': 'Telefon',
    'contact.info.address': 'Manzil',
    'contact.hours.title': 'Ish vaqti',
    'contact.hours.weekday': 'Dushanba - Juma',
    'contact.hours.weekdayTime': '9:00 - 18:00',
    'contact.hours.saturday': 'Shanba',
    'contact.hours.saturdayTime': '10:00 - 16:00',
    'contact.hours.sunday': 'Yakshanba',
    'contact.hours.sundayTime': 'Dam olish',
    'contact.social.title': 'Bizni kuzatib boring',
    'contact.map.title': 'Interaktiv xarita',
    'contact.map.description': 'Bizni 123 Education Street da toping',
    
    // Dashboard
    'dashboard.welcome': 'Xush kelibsiz,',
    'dashboard.subtitle': 'Oʻquv rivojlanishingiz va mukofotlaringizni kuzatib boring',
    'dashboard.totalCoins': 'Jami tangalar',
    'dashboard.thisWeek': 'bu hafta',
    'dashboard.achievements': 'Yutuqlar',
    'dashboard.newMonth': 'bu oyda yangi',
    'dashboard.streak': 'Hozirgi ketma-ketlik',
    'dashboard.days': 'kun',
    'dashboard.keepUp': 'Davom eting!',
    'dashboard.rewardHistory': 'Mukofotlar tarixi',
    'dashboard.trackAll': 'Barcha qazonilib olingan tangalar va yutuqlarni kuzatib boring',
    'dashboard.filterType': 'Turi boʻyicha filtrlash',
    'dashboard.allActivities': 'Barcha faoliyatlar',
    'dashboard.homework': 'Uy vazifasi',
    'dashboard.quizzes': 'Testlar',
    'dashboard.achievements': 'Yutuqlar',
    'dashboard.participation': 'Ishtirok',
    'dashboard.bonus': 'Bonus',
    'dashboard.referrals': 'Tavsiyalar',
    'dashboard.noActivities': 'Ushbu filtr uchun faoliyat topilmadi',
    'dashboard.home': 'Bosh sahifa',
    'dashboard.dashboard': 'Panel',
    'dashboard.courses': 'Mening kurslarim',
    'dashboard.profile': 'Profil',
    
    // Activities
    'activity.completedMathQuiz': 'Ilg\'or matematika testini tugatdi',
    'activity.submittedPhysics': 'Fizika topshirig\'ini topshirdi',
    'activity.learningStreak': '7 kunlik oʻrganish ketma-ketligi',
    'activity.activeDiscussion': 'Faol muhokama ishtiroki',
    'activity.acedEnglish': 'Ingliz adabiyoti testidan ajoyib oʻtdi',
    'activity.earlySubmission': 'Erta topshirish bonusi',
    'activity.chemistryLab': 'Kimyo laboratoriya hisoboti',
    'activity.referredFriend': 'Doʻstni tavsiya qildi',
    'activity.completedCourse': 'Kursni tugatdi: Veb dasturlash',
    'activity.historyQuiz': 'Tarix testi mukammal ball',
    
    // Categories
    'category.math': 'Matematika',
    'category.science': 'Fan',
    'category.milestone': 'Muhim bosqich',
    'category.community': 'Jamiyat',
    'category.english': 'Ingliz tili',
    'category.bonus': 'Bonus',
    'category.referral': 'Tavsiya',
    'category.achievement': 'Yutuq',
    'category.history': 'Tarix',
    
    // Team Members
    'team.ceo': 'Bosh direktor va asoschisi',
    'team.cto': 'Bosh texnologiya direktori',
    'team.education': 'Ta\'lim boʻlimi rahbari',
    'team.product': 'Mahsulot menejeri',
    
    // Leaderboard
    'leaderboard.title': 'Reyting jadvali',
    'leaderboard.subtitle': 'Eng yaxshi ishtirokchilar va ularning yutuqlari',
    'leaderboard.students': 'Talabalar',
    'leaderboard.teachers': 'Oʻqituvchilar',
    'leaderboard.admins': 'Administratorlar',
    'leaderboard.rank': 'O\'rin',
    'leaderboard.name': 'Ism',
    'leaderboard.currentBalance': 'Joriy balans',
    'leaderboard.allTimeBalance': 'Umumiy balans',
    'leaderboard.actions': 'Harakatlar',
    'leaderboard.current': 'Joriy',
    'leaderboard.allTime': 'Umumiy',
    'leaderboard.view': 'Ko\'rish',
    'leaderboard.hide': 'Yashirish',
    'leaderboard.transactionHistory': 'Tranzaksiyalar tarixi',
    'leaderboard.type': 'Turi',
    'leaderboard.description': 'Tavsif',
    'leaderboard.amount': 'Miqdor',
    'leaderboard.date': 'Sana',
    'leaderboard.page': 'Sahifa',
    'leaderboard.of': 'dan',
    'leaderboard.previous': 'Oldingi',
    'leaderboard.next': 'Keyingi',
    'leaderboard.topPerformer': 'Eng yaxshi',
    'leaderboard.excellent': 'A\'lo',
    'leaderboard.great': 'Yaxshi',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('ilmcoin-language') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('ilmcoin-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'uz' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
